id: IB3995BBC
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-27T11:22:48+00:00'
last_modified: '2022-06-09T04:52:49.671665+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG24477
  title: གསུང་འབུམ། བློ་བཟང་ཆོས་འབྱོར་ལྷུན་གྲུབ།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
  base:
    BFB0:
      image_group_id: I1KG24497
      title: Volume 1 of gsung 'bum/_blo bzang chos 'byor lhun grub/
      total_pages: 920
      order: 1
      base_file: BFB0.txt
    CF66:
      image_group_id: I1KG24498
      title: Volume 2 of gsung 'bum/_blo bzang chos 'byor lhun grub/
      total_pages: 880
      order: 2
      base_file: CF66.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
