id: IB3995BBC
legacy_id: P008154
ocr_import_info:
  bdrc_scan_id: W1KG24477
  source: bdrc
  ocr_info:
    timestamp: '2020-03-27T11:17:18'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-08-31T13:44:32.165310+00:00'
last_modified: 2022-08-31 21:46:43.300839
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W1KG24477
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  geo_restriction:
  - CN
  reproduction_of: http://purl.bdrc.io/resource/MW1KG24477
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: གསུང་འབུམ། བློ་བཟང་ཆོས་འབྱོར་ལྷུན་གྲུབ།
  author: རོང་ཐ་ཆེ་ཚང ༠༤་བློ་བཟང་ཆོས་འབྱོར་ལྷུན་གྲུབ།
statistics:
  ocr_word_mean_confidence_index: 0.939437305745649
  ocr_word_median_confidence_index: 0.9800000190734863
quality: null
bases:
  I1KG24498:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG24498
      total_pages: 880
      volume_number: 2
      volume_pages_bdrc_intro: 2
    order: 2
    base_file: I1KG24498.txt
    statistics:
      ocr_word_median_confidence_index: 0.9800000190734863
      ocr_word_mean_confidence_index: 0.9445344456926897
    legacy_id: v002
  I1KG24497:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG24497
      total_pages: 920
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I1KG24497.txt
    statistics:
      ocr_word_median_confidence_index: 0.9800000190734863
      ocr_word_mean_confidence_index: 0.9335933683266975
    legacy_id: v001
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
