id: P008154
initial_creation_type: ocr
source_metadata:
  id: bdr:W1KG24477
  title: གསུང་འབུམ། བློ་བཟང་ཆོས་འབྱོར་ལྷུན་གྲུབ།
  author: ''
  volumes:
    3d618bf00aff483d985181143e52d7a1:
      image_group_id: I1KG24497
      title: Volume 1 of gsung 'bum/_blo bzang chos 'byor lhun grub/
      volume_number: 1
      total_pages: 920
      base_file: v001.txt
    14aa58b045de4a60b92260b139b704b6:
      image_group_id: I1KG24498
      title: Volume 2 of gsung 'bum/_blo bzang chos 'byor lhun grub/
      volume_number: 2
      total_pages: 880
      base_file: v002.txt
ebook_metadata:
  title: གསུང་འབུམ། བློ་བཟང་ཆོས་འབྱོར་ལྷུན་གྲུབ།
  author: ''
  sku: P008154
  cover: cover.jpg
  layers:
  - pagination
