id: P008154
initial_creation_type: ocr
source_metadata:
  id: bdr:W1KG24477
  title: གསུང་འབུམ། བློ་བཟང་ཆོས་འབྱོར་ལྷུན་གྲུབ།
  author: ''
  volumes:
    3dc837e4f2cf4b7c98524ab0dc185061:
      image_group_id: I1KG24497
      title: ''
      volume_number: 1
      total_pages: 920
    b5563cdea07b4a6da40b3d787b922e37:
      image_group_id: I1KG24498
      title: ''
      volume_number: 2
      total_pages: 880
ebook_metadata:
  title: གསུང་འབུམ། བློ་བཟང་ཆོས་འབྱོར་ལྷུན་གྲུབ།
  author: ''
  sku: P008154
  cover: cover.jpg
  layers:
  - pagination
